Finished tests for classroom-service
hekkaaa/Bear-goodbye-kolkhoz pull request #118
Opened 2022-03-29 14:07 UTC by klokgd

1. Updated methods for classrooms to implement soft-delete;
2. Finished unit-tests

2022-03-29 14:41 UTC, hekkaaa commented on BGK.Data/Repositories/ClassroomRepository.cs
> +        public bool UpdateClassroomInfo(Classroom oldItem, bool isDeleted)
Слушай, а тебя название метода не смущает? Да мы обновляем по сути данные тут, но по факту идет разбан.
Если обратишь внимание на имя метода в Сервисе, которое ты сам написал **RestoreClassroom** - то логичнее было бы метод так и назвать в репозитории?
Как ты на это смотришь?

2022-03-29 16:34 UTC, klokgd commented on BGK.Data/Repositories/ClassroomRepository.cs
> +        public bool UpdateClassroomInfo(Classroom oldItem, bool isDeleted)
Всё так, поправлю

2022-03-29 16:35 UTC, klokgd commented on BGK.Data/Repositories/ClassroomRepository.cs
> +        public bool UpdateClassroomInfo(Classroom oldItem, bool isDeleted)
А, нет, неверно. На уровне репозитория это один и тот же update-метод - на аптейд, на удаление и на восстановления.

2022-03-29 16:41 UTC, hekkaaa commented on BGK.Data/Repositories/ClassroomRepository.cs
> +        public bool UpdateClassroomInfo(Classroom oldItem, bool isDeleted)
Я вижу что репозиторий который ты используешь хардкодом вписывает true. Как он тогда удаляет и восстанавливает? Ведь значение bool должно меняться false\true.

2022-03-29 18:14 UTC, klokgd commented on BGK.Data/Repositories/ClassroomRepository.cs
> +        public bool UpdateClassroomInfo(Classroom oldItem, bool isDeleted)
Поправил! Тут мой косяк

2022-03-30 15:29 UTC, hekkaaa requested changes

2022-03-30 15:29 UTC, hekkaaa commented on BGK.Business/Services/ClassroomService.cs
> +                throw new NotFoundException("");
А почему ошибку просто " " оставляешь? Впиши туда нужный текст который улетит вместе с ним. На 26 строчке в том же файле ты отправляешь.

2022-03-30 15:29 UTC, hekkaaa commented on BGK.Data/Repositories/ClassroomRepository.cs
> +            _db.Classroom.Where(c => c.MembersCount >= sitCount).ToList();
А что делает этот репозиторный метод? Он явно к софт-делит не относится. К тестам тоже. 
Зачем он реализован?

2022-03-30 15:41 UTC, klokgd commented on BGK.Data/Repositories/ClassroomRepository.cs
> +            _db.Classroom.Where(c => c.MembersCount >= sitCount).ToList();
Не знаю, почему тут изменения, его не трогал

2022-03-30 15:43 UTC, klokgd commented on BGK.Business/Services/ClassroomService.cs
> +                throw new NotFoundException("");
Исправил

2022-03-30 16:01 UTC, Alehandro03 approved these changes

2022-03-30 16:08 UTC, klokgd commented on BGK.Data/Repositories/ClassroomRepository.cs
> +            _db.Classroom.Where(c => c.MembersCount >= sitCount).ToList();
Там же ничего не поменялось, просто метод передвинулся к низу

2022-03-30 16:39 UTC, merged