BGK-40
hekkaaa/Bear-goodbye-kolkhoz pull request #84
Opened 2022-03-07 14:27 UTC by AzarovRoman

2022-03-07 17:04 UTC, hekkaaa requested changes
Тесты полетели в тар тарары

2022-03-07 17:04 UTC, hekkaaa commented on BearGoodbyeKolkhozProject.Data.Tests/TestCaseSources/EventTestCaseSource/GetEventByIdTestCaseSource.cs
> +                        Password = "12345"
![image](https://user-images.githubusercontent.com/46771781/157082231-e27fdb79-5772-4e07-b1fe-605484ae52a9.png)

2022-03-07 17:09 UTC, hekkaaa commented on BearGoodbyeKolkhozProject.Data.Tests/TestCaseSources/EventTestCaseSource/GetEventByIdTestCaseSource.cs
> +                        Password = "12345"
Исправил, но не заливал пока.
Не верно копировал данные, много using не подлечено в тесты.

![image](https://user-images.githubusercontent.com/46771781/157082871-a060cab8-6092-487d-bb6f-8107c7bedb55.png)

2022-03-07 17:42 UTC, hekkaaa commented on BGK.Business/Services/EventService.cs
> +            foreach(EventModel model in eventModels)
данном месте не учитывается, что лектор может быть НЕ назначен ни на какой тренинг.
 
![image](https://user-images.githubusercontent.com/46771781/157087301-74f500c0-c775-4d06-8c02-fc54039d90c0.png)

Предлагаю добавить:
`   if(eventModels.Count is 0)
            {
                throw new BusinessException("The lecturer does not participate in any training | Лектор не учавствует ни в одном тренинге");
            }
`

2022-03-07 18:30 UTC, hekkaaa requested changes

2022-03-07 18:30 UTC, hekkaaa commented on BGK.Business/Services/EventService.cs
> +            }
![image](https://user-images.githubusercontent.com/46771781/157095644-9411d10a-9d47-4806-a752-38d11f122644.png)

2022-03-07 18:34 UTC, hekkaaa commented on BGK.Business/Services/EventService.cs
> +            }
Нет ни какого прайса в EventModel. Видимо бы ее не тянешь. Прайс находится в Traning
![image](https://user-images.githubusercontent.com/46771781/157096227-983d7a3e-f66c-47f9-b1c4-f715218eac0b.png)

2022-03-07 18:43 UTC, hekkaaa commented on BGK.Business/Services/EventService.cs
> +            }
Нам получается не хватает загрузки Traning в методе который ты дергаешь.
Сложно оценить как это повлияет на другие методы дергающие его. ПО этому предлагаю реализовать нужный запрос в нашем методе GetCompletedEventsByLecturer

![image](https://user-images.githubusercontent.com/46771781/157097427-d710c45c-d13b-4fe9-aaff-0406abecad76.png)

2022-03-07 19:17 UTC, hekkaaa commented on BGK.Business/Services/EventService.cs
> +            }
Метод **GetClosedRegEvents** дергается методом **SingUp**. 
Проверил, проблем нет в его работе с данной правкой.

Варианта один: Оставляем так, но будут тянутся не нужные данные сейчас через **Include** по **Traning**.
Вариант два: пишем отдельный приватный метод т.к **GetClosedRegEvents** дергается  `GetAttendedEventsByClient(Client client, DateTime date)` где так же ценник показывается.

2022-03-07 19:21 UTC, hekkaaa requested changes

2022-03-07 19:21 UTC, hekkaaa commented on BearGoodbyeKolkhoz.API/Controllers/EventsController.cs
> +        [ProducesResponseType(StatusCodes.Status200OK)]
Метод не возвращает **название тренинга** по требованию задачи.

![image](https://user-images.githubusercontent.com/46771781/157103177-0292a751-53b9-4cbf-9203-9922ec44edee.png)

2022-03-07 20:00 UTC, hekkaaa commented on BearGoodbyeKolkhoz.API/Controllers/EventsController.cs
> +        [ProducesResponseType(StatusCodes.Status200OK)]
Реализовал у себя. Через добавление в **EventModel** и **CompletedEventsOutputModel** ->  `public string? Name { get; set; }`

В сервисах забирал из вложенной таблицы Traning прайс и докидывал в свойство Name.
`model.Name = model.Training.Name;`

![image](https://user-images.githubusercontent.com/46771781/157108479-ae65f58d-35c8-4a52-a536-937dceb2c5a6.png)

2022-03-07 21:10 UTC, hekkaaa commented
Посыпятся тесты если внести мои изменения.

![image](https://user-images.githubusercontent.com/46771781/157118337-9698e6c7-824c-45f9-81b0-b71a68d487f6.png)

2022-03-08 10:39 UTC, AzarovRoman commented on BGK.Business/Services/EventService.cs
> +            foreach(EventModel model in eventModels)
Если лектор не провел ни одного тренинга, то просто вернется пустой список.
(Антон говорил что если нужно вернуть список чего-то, то пустой список - это тоже успех)

2022-03-08 10:54 UTC, AzarovRoman commented on BGK.Business/Services/EventService.cs
> +            }
если include работает, то я за него

2022-03-08 11:21 UTC, hekkaaa commented on BGK.Business/Services/EventService.cs
> +            foreach(EventModel model in eventModels)
Ну потом нам вика вернет и скажет "ну и где хоть что-то!? Переделывайте"

2022-03-08 19:47 UTC, hekkaaa approved these changes

2022-03-08 19:54 UTC, klokgd approved these changes

2022-03-08 20:03 UTC, merged